[package]
name = "plain-state-machine-hype-train"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.32.0", features = ["full"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
